### PR TITLE
Major Improvement

### PR DESCRIPTION
**Pull request by kawaii-ghost**
Distinct present tense and past tense.
Change some words into familiar and standard one
Add Disclaimer translator
*Not blindy copy-paste from translator engine and call it translation

### CODE REVIEW

**Review by SyrmGIT — APPROVED** [review]

**Review by SyrmGIT — CHANGES_REQUESTED** [review]
Do not translate the disclaimer. This is against our translation readme rules.

**Comment by PencilNavigator** [comment]
> Do not translate the disclaimer. This is against our translation readme rules.

Syrm, In view files, the disclaimer is actually not translated.

**Review by PencilNavigator — APPROVED** [review]
Checked with DeepL, looks good.

**Comment by uncognic** [comment]
> > Do not translate the disclaimer. This is against our translation readme rules.
> 
> Syrm, In view files, the disclaimer is actually not translated.

it *shouldn't* be translated

**Comment by PencilNavigator** [comment]
> > > Do not translate the disclaimer. This is against our translation readme rules.
> > 
> > 
> > Syrm, In view files, the disclaimer is actually not translated.
> 
> it _shouldn't_ be translated

yes, that's true.

**Comment by kawaii-ghost** [comment]
> Do not translate the disclaimer. This is against our translation readme rules.

Sorry, seems like i didn't use the latest commit

**Pull request merged**
