### PR TITLE
General translation formatting fixes

### PR DESCRIPTION
**Pull request by SnowzNZ**
### Questions
- ~~[ ] Did you test your changes or double check that they work?~~ (N/A)
- [x] Did you read and follow the [Atlas Contribution Guidelines](https://docs.atlasos.net/contributions/)?
- ~~[ ] Did you commit to the [`dev`](https://github.com/Atlas-OS/Atlas/tree/dev) branch and not [`main`](https://github.com/Atlas-OS/Atlas)?~~ (N/A)

**Note:** You should commit directly to `main` for translations of the `README.md`.

### Describe your pull request

General translation formatting fixes

### CODE REVIEW

**Comment by JayXTQ** [comment]
Hi, do you know the word for disclaimer in all these languages or no? Because we don’t want translated documentation really as it can cause incorrect grammar, punctuation and the likes

**Comment by he3als** [comment]
As it's a single word presumably, I think that it's acceptable

**Comment by SnowzNZ** [comment]
> Hi, do you know the word for disclaimer in all these languages or no? Because we don’t want translated documentation really as it can cause incorrect grammar, punctuation and the likes

I've cross-checked translators and other websites.

**Review by he3als — APPROVED** [review]
Checked with Google Translate and other online dictionaries, it all seems to be correct.

**Review by Xyueta — APPROVED** [review]

**Pull request merged**
