### PR TITLE
Add support for Microsoft Accounts for UWP and Store + UAC disable warning

### PR DESCRIPTION
**Pull request by he3als**
If a user tries to run a script that disables Store or UWP while having a Microsoft Account on their computer, the wlidsvc will not be disabled so they can sign in.

I also added a disable UAC warning.

### CODE REVIEW

**Comment by he3als** [comment]
image
I did not understand what you meant by the first one, so I will leave that up to you to edit. I did 2 and 3

**Comment by Zusier** [comment]
This should do the trick, written on a mac. So I can't test yet.

**Comment by he3als** [comment]
Seems fine to me, nice job

**Comment by Zusier** [comment]
It's working, thanks for the PR once again!

**Pull request merged**
