### PR TITLE
Turkish Translation / Türkçe Çeviri

### PR DESCRIPTION
**Pull request by imribiy**
Turkish Translation for users.

### CODE REVIEW

**Review by PencilNavigator — CHANGES_REQUESTED** [review]
Please delete line 18-30, Language changer in Translated docs are not nesscery.

**Comment by imribiy** [comment]
OK

**Comment by PencilNavigator** [comment]
Do not translate the disclaimer.
https://github.com/Atlas-OS/Atlas/blob/main/translations/README.md

**Comment by imribiy** [comment]
wheeeeew

**Review by PencilNavigator — APPROVED** [review]
Rough check with DeepL, looks good.

**Comment by imribiy** [comment]
Yeah some idioms like potato pc doesnt make any sense in Turkish, some minor changes have been made.

**Comment by PencilNavigator** [comment]
> Yeah some idioms like potato pc doesnt make any sense in Turkish, some minor changes have been made.

Calcaulator LOL, yeah that makes sense.

**Comment by Xyueta** [comment]
Excellent job. Merging

**Review by Xyueta — APPROVED** [review]

**Pull request merged**
