### PR TITLE
[PR] Disable Automatic Folder Discovery

### PR DESCRIPTION
**Pull request by the-P1neapple**
### Questions
- [x] Did you test your changes or double check that they work?
- [x] Did you read and follow the [Atlas Contribution Guidelines](https://docs.atlasos.net/contributions/)?
- [x] Did you commit to the [`dev`](https://github.com/Atlas-OS/Atlas/tree/dev) branch and not [`main`](https://github.com/Atlas-OS/Atlas)?

### Describe your pull request

This is a patch based on the Shell Bags Registry which is in charge of custom view properties when loading a folder. Disabling this has potential to speed up indexing on older hard drives by preventing automatic view changes based on the content present in the folder.

### CODE REVIEW

**Comment by Xyueta** [comment]
looks good to me

**Comment by he3als** [comment]
Automatic folder discovery is useful for selecting certain views in Explorer, such as your 'Pictures' folder being set to thumbnail/icon view by default.

Disabling it by default can annoy some users, including me when I used to use this tweak.

To disable it by default, it would be best to have a good confirmation of how this speeds up Explorer first. Additionally, there should be `Optional Tweaks` Registry files to toggle the feature.

**Comment by Xyueta** [comment]
https://twitter.com/unitycoder_com/status/1764550045070721212

**Comment by the-P1neapple** [comment]
> https://twitter.com/unitycoder_com/status/1764550045070721212

I originally found out about this tweak from Endermanch in his telegram but I didn't realise it was this effective.
@he3als do you want me to still want me to put this in optional tweaks or in the main configuration folder?

**Comment by he3als** [comment]
In that case, it can be disabled by default then as a performance over QoL tweak

**Pull request merged**
