### PR TITLE
Update Atlas-config.bat and remove folders

### PR DESCRIPTION
**Pull request by Vojtazz**
Changed HKEY_* to HKCU, HKLM, HKCR.
Removed Keyboard Data Queues Size (possible placebo or cause mouse being laggy).
Fixed environment variable __COMPAT_LAYER registry.
Commented DevManView value which can cause problems with games.
Added GOG and Uplay apps are now set to below priority.
Small changes in the script look.

### CODE REVIEW

**Comment by Zusier** [comment]
I’m sorry.. making all of these changes in one PR is not the right way to do it. I specifically didnt do HKLM to make it more readable. I’ll integrate changes with credits

**Comment by yCyanxs** [comment]
Delete the DataQueues for the mouse & kbd is useless, it's called optional tweaks for a reason, for testing. And changing the script for visibility won't do as well, if it works then it works. I like the idea for removing possible placebo changes in the registry but it's "possible" its a tweak nonetheless so keeping it is still fine.

**Comment by Vojtazz** [comment]
Theoretically you are right. From my testing it caused not better results. Therefore i removed it.

**Comment by Vojtazz** [comment]
:)

**Pull request closed without merging**
