### PR TITLE
Migrate issues to Atlas forum

### PR DESCRIPTION
**Pull request by PencilNavigator**
Discussed in the Atlas discord, Issues will probably make the move to Forums in future.

-Changed the config.yml for issues to point all to the Atlas forums.
-Deleted bug-report.yml and feature-request.yml since after the migration we don't need it anymore.

This is set as a Draft since the migration isn't coming immediately.

### CODE REVIEW

**Comment by he3als** [comment]
Why would GitHub issues move to the forums?

**Comment by JayXTQ** [comment]
Syrm said he wanted to in the future

**Comment by SyrmGIT** [comment]
> Syrm said he wanted to in the future

Possibly, still not set in stone. I need to fully evaluate what the best choice is before anything.

**Comment by he3als** [comment]
It doesn't make sense to, a bug reporting place (GitHub issues) and a forum aren't the same thing, and people would expect the bug reports to be on GitHub with the repo.

**Comment by PencilNavigator** [comment]
> It doesn't make sense to, a bug reporting place (GitHub issues) and a forum aren't the same thing, and people would expect the bug reports to be on GitHub with the repo.

Ublock seperated it's issue from its original repo.
https://github.com/gorhill/uBlock/issues/3726

**Comment by he3als** [comment]
Yes but why would Atlas?

**Comment by PencilNavigator** [comment]
This pull request is closed because i need to commit a small fix on the README document and also all translated versions.

**Comment by jamesbt365** [comment]
Just use branches?

**Comment by PencilNavigator** [comment]
> Just use branches?

its easier for me to just delete the repo and re-fork it.

**Pull request closed without merging**
