### PR TITLE
ADD: ITALIAN translation to README

### PR DESCRIPTION
**Pull request by arun99-dev**

### CODE REVIEW

**Review by JayXTQ — APPROVED** [review]
Gone ahead and translated parts of this and it LGTM, maybe you should add the italian flag to the main readme.md as well (the one in root)

**Comment by JayXTQ** [comment]
Going to add flag now

**Review by JayXTQ — APPROVED** [review]
added flag, LGTM

**Review by PencilNavigator — APPROVED** [review]
deepl check good

**Pull request merged**
