### PR TITLE
Fix Windows keep freezing

### PR DESCRIPTION
**Pull request by Netxv**
This bug occur for a while (since January 19) when Xyueta forgot to revert the changes which causes Windows 22H2 ( SVCHost.exe) to be unresponsive for a while

### CODE REVIEW

**Comment by PencilNavigator** [comment]
Referencing Issuehttps://github.com/Atlas-OS/Atlas/issues/572

**Comment by Xyueta** [comment]
Are you sure about that? Those servcies are not related to svchost.

**Comment by Xyueta** [comment]
Do NOT translate Disclaimer.

**Comment by Netxv** [comment]
> Are you sure about that? Those servcies are not related to svchost.

Im not sure its related to svchost 100% but it actually fix the freezing loop.

**Comment by Netxv** [comment]
> Do NOT translate Disclaimer.

Ok sry about that :( I didnt fully read it

**Comment by Xyueta** [comment]
Resolved in https://github.com/Atlas-OS/Atlas/commit/7faf7b80e7d180353ca2993868c5ff6b2037b96a, make a new pr for vietnamese translation changes. 

Thanks.

**Comment by PencilNavigator** [comment]
@Xyueta most changes for vietnamese translation is unnesscery (expect the "possible information retrival" thing which i already changed), translations should stay in the same format as the original one.

**Comment by Xyueta** [comment]
all right, thank you.

**Pull request closed without merging**
