### PR TITLE
multiple changes to README and it's translation

### PR DESCRIPTION
**Pull request by PencilNavigator**
### Questions
- [ ] Did you test your changes or double check that they work?
- [ ] Did you read and follow the [Atlas Contribution Guidelines](https://docs.atlasos.net/contributions/)?
- [ ] Did you commit to the [`dev`](https://github.com/Atlas-OS/Atlas/tree/dev) branch and not [`main`](https://github.com/Atlas-OS/Atlas)?

**Note:** You should commit directly to `main` for translations of the `README.md`.

### CODE REVIEW

**Review by Xyueta — APPROVED** [review]

**Review by JayXTQ — COMMENTED** [review]
Why?

**Review by Xyueta — CHANGES_REQUESTED** [review]
why?

**Comment by PencilNavigator** [comment]
give credits to translators (which most of our translation does).

**Comment by PencilNavigator** [comment]
hold on, i found more issues.
lemme add more to this pr.

**Comment by PencilNavigator** [comment]
- changed banner link from `cdn.jsdelivr.net` to `gcore.jsdelivr.net` due to cdn prefix having a propability not able to show pictures.

**Review by JayXTQ — CHANGES_REQUESTED** [review]
I'd recommend saying "add translation contributors to the bottom of the page" rather than displaying octocat and mona

**Review by JayXTQ — DISMISSED** [review]
LGTM

**Review by Xyueta — DISMISSED** [review]

**Review by Xyueta — APPROVED** [review]

**Review by JayXTQ — APPROVED** [review]
3rd times the charm no?

**Review by Xyueta — APPROVED** [review]

**Pull request merged**
