### PR TITLE
Remove Disney+ and Spotify bloatware appx.

### PR DESCRIPTION
**Pull request by K4F0**

### CODE REVIEW

**Comment by JayXTQ** [comment]
None of these apps you have made a pr for exist on my machine and I’m running a commit made today. Do you have evidence that you have them on your machine?

**Comment by Xyueta** [comment]
@K4F0 Did you install your Windows without the internet and did you use our OOBE Guide - skip unnecessary Windows settings in there?

Thanks.

**Comment by K4F0** [comment]
Yes, I followed the instructions exactly as they should be followed for a proper installation.

**Comment by ChecksumDev** [comment]
I can add on to this that oddly after my complete install as per the instructions disney plus was also there, though it was the only form of bloatware. 

I personally use Spotify and installed it via their executable installer so I'm not entirely sure if Spotify was removed either.

**Comment by Xyueta** [comment]
Did you install any updates?

**Comment by K4F0** [comment]
Yes, after applying the .reg file I updated

**Comment by ChecksumDev** [comment]
Nope, my clean installation was a couple hours after .2 released and Windows was fully up to date when I ran the playbook

**Comment by JayXTQ** [comment]
I have just seen a twitter thread where a user installs atlas and yes, it shows disney+ still existing after installing atlas but it's not entirely installed? it's weird. so this does happen a bit then it seems

**Review by Xyueta — APPROVED** [review]

**Pull request merged**
