### PR TITLE
removed unnecessary capitals

### PR DESCRIPTION
**Pull request by uncognic**

### CODE REVIEW

**Comment by 0bo** [comment]
Thank you for your "contribution" , but this is absolute nonsense.

I guess you doing this to try to cheat a "contributor" tag, right?

Do something meaningful, but racist abusing people under issues or creating rubbish pull request here.

**Comment by uncognic** [comment]
Bro, I already have the contributor role, and for the China thing, i didn't know that it had gotten so popular

**Comment by PencilNavigator** [comment]
> Bro, I already have the contributor role, and for the China thing, i didn't know that it had gotten so popular

its not just about popular or not, is the way you speak.

That person needs help installing chinese, and instead of helping him you choose to cyberbully him.
and as you might see there are guides about installing slimplified chinese on this OS and Windows itself do support chinese, so the only thing needed to do is to install the language pack for it (since AtlasOS removed it).

Not everyone on this world speaks english, and chinese is also a world language (the reason why you see translation of chinese on the united nations website).

Respect others, and others will respect you.

**Comment by JayXTQ** [comment]
Submit the PR. It will get checked out.

**Pull request merged**
