### PR TITLE
Adds Portuguese translation of README

### PR DESCRIPTION
**Pull request by pedrosilva17**
Related to #718
Translated the text in the README.md file and updated Microsoft links to their respective Portuguese versions.

### CODE REVIEW

**Comment by Xyueta** [comment]
https://github.com/Atlas-OS/Atlas/blob/main/translations/README_pt_BR.md

**Comment by pedrosilva17** [comment]
Does it have to do with maintaining two variants of the same language? I have to admit it's a bit disappointing to see one being replaced by the other so often, but I do understand that the benefit is almost negligible compared to the additional work. Regardless, happy to help!

**Comment by JayXTQ** [comment]
Are they both the same in like files or no? Because if not I will include a portuguese flag in root!

**Comment by pedrosilva17** [comment]
There shouldn't be changes in files other than text. They are similar variants in the sense that a speaker of one of them can understand the other (for the most part), but there are some notable differences

**Comment by JayXTQ** [comment]
Ok, then shouldn't we push if there is differences? @Xyueta

**Pull request closed without merging**
