### PR TITLE
Update README_zh_CN.md

### PR DESCRIPTION
**Pull request by magisk317**
Translation files should return to the main page instead of looping，and some minor formatting adjustments

### CODE REVIEW

**Comment by JayXTQ** [comment]
I would say, this should be done to every other translation file if so, also, unnecessary change of character, unless that is not a Chinese character that you changed.

**Comment by magisk317** [comment]
> I would say, this should be done to every other translation file if so, also, unnecessary change of character, unless that is not a Chinese character that you changed.

Sorry, I'm Chinese, so I only followed the Simplified Chinese page. What you said is indeed an issue. I don’t know why other translators don’t put English first but Chinese. Maybe the translator is also Chinese?

**Comment by SyrmGIT** [comment]
You should make the same changes on the other language pages too.

**Comment by JayXTQ** [comment]
> Sorry, I'm Chinese, so I only followed the Simplified Chinese page. What you said is indeed an issue. I don’t know why other translators don’t put English first but Chinese. Maybe the translator is also Chinese?

The translator of the original Chinese version is Chinese iirc.

**Comment by magisk317** [comment]
> You should make the same changes on the other language pages too.

Maybe the format is ok, please help to review

**Comment by magisk317** [comment]
Language order has been adjusted

**Review by SyrmGIT — APPROVED** [review]

**Pull request merged**
