### PR TITLE
feat: ✨ask if user wants password entry on UAC

### PR DESCRIPTION
**Pull request by JayXTQ**
### Questions
- [ ] Did you test your changes or double check that they work?
- [ ] Did you read and follow the [Atlas Contribution Guidelines](https://docs.atlasos.net/contributions/)?
- [ ] Did you commit to the [`dev`](https://github.com/Atlas-OS/Atlas/tree/dev) branch and not [`main`](https://github.com/Atlas-OS/Atlas)?

**Note:** You should commit directly to `main` for translations of the `README.md`.

### Describe your pull request
remake of my other pr which i stupidly sent to main

### CODE REVIEW

**Comment by JayXTQ** [comment]
#778 is my old PR

**Comment by JayXTQ** [comment]
waiting...

**Comment by he3als** [comment]
I don't really think that this would be necessary, I'd rather have the main option of converting your account into a standard/non-administrator account for security purposes.

**Comment by Xyueta** [comment]
Closing then, I also do not think that it is a valid solution to introduce in Atlas.

**Pull request closed without merging**
