### PR TITLE
Slimplified Chinese README

### PR DESCRIPTION
**Pull request by PencilNavigator**
Grammar inproved https://github.com/Atlas-OS/Atlas/pull/332.

### CODE REVIEW

**Comment by 0bo** [comment]
我已关闭我的那个pr了，另外这个好像没有提交对主readme的那部分更改哈

**Comment by JayXTQ** [comment]
Just reading through this even though I do not understand Chinese. I noticed that this is not a .md file, which it probably should be for readability. You may want to consider changing that so it's not all in code format

**Comment by PencilNavigator** [comment]
> Just reading through this even though I do not understand Chinese. I noticed that this is not a .md file, which it probably should be for readability. You may want to consider changing that so it's not all in code format

Fixed. I forgot to add the extention name, Thank you for pointing that out!

**Comment by JayXTQ** [comment]
Thank you for changing into a .md file. I have gone through the file with [DeepL Translate](https://www.deepl.com/en/translator) to translate back into English to make sure everything is correct. From what looks like it, that is a very good translation into Chinese for all of the Chinese users. I should probably let other Chinese people read this to check if everything is correct instead though.

**Comment by PencilNavigator** [comment]
> Thank you for changing into a .md file. I have gone through the file with [DeepL Translate](https://www.deepl.com/en/translator) to translate back into English to make sure everything is correct. From what looks like it, that is a very good translation into Chinese for all of the Chinese users. I should probably let other Chinese people read this to check if everything is correct instead though.

You're welcome, and also credits for https://github.com/0bo

**Review by xyzze — APPROVED** [review]
translation is correct

**Review by SyrmGIT — APPROVED** [review]

**Review by JayXTQ — APPROVED** [review]

**Pull request merged**
