### PR TITLE
Complete Restructure of the Playbook's Tweaks & Main -> Dev

### PR DESCRIPTION
**Pull request by he3als**
### Questions
- [x] Did you test your changes or double check that they work?
- [x] Did you read and follow the [Atlas Contribution Guidelines](https://docs.atlasos.net/contributions/)?
- [x] Did you commit to the [`dev`](https://github.com/Atlas-OS/Atlas/tree/dev) branch and not [`main`](https://github.com/Atlas-OS/Atlas)?

**Note:** You should commit directly to `main` for translations of the `README.md`.

### Describe your pull request
Completely restructures the playbook's tweaks into having each tweak its separate file, instead of having one very long `config.yml` with every tweak.

There is a central [`tweaks.yml`](https://github.com/Atlas-OS/Atlas/blob/playbook-refactor/src/Configuration/tweaks.yml) with all of the tweak files that are ran, with categories.

This **pull request should be merged with a merge commit, not squash or rebase**.

#### Advantages
1. More easily measure the amount of tweaks
2. Proper description and title for tweaks
   - Forces good organisation
   - Allows people to more easily judge tweaks on if they're good or not
3. Easily troubleshoot issues
4. Easily sort out the good tweaks from the bad

### CODE REVIEW

**Comment by JayXTQ** [comment]
201 file changes? here we go...

**Comment by JayXTQ** [comment]
i cant tell if there is any actual code changes here except from rerouting to the new file system you have going on. is there changes other than just reformatting the playbook?

**Comment by he3als** [comment]
There might be minor changes?

**Comment by he3als** [comment]
See https://github.com/Atlas-OS/Atlas/blob/playbook-refactor/src/Configuration/tweaks.yml for the main file to review.

**Review by RadNotRed — APPROVED** [review]

**Comment by osenaattori** [comment]
naps

**Review by SyrmGIT — DISMISSED** [review]

**Review by SyrmGIT — APPROVED** [review]

**Review by RadNotRed — APPROVED** [review]
💥

**Pull request merged**
