### PR TITLE
correction du français

### PR DESCRIPTION
**Pull request by osafaimal**
I have see that you have a french traduction but honestly sometimes i didn't understand the ideas behind the sentences thus i have decided to propose changes that i think are more understandable. I left some translations that are weird for me but may not be for a Canadian (in France we use a lot of English words unlike Canada which tries to translate everything into good French).

### CODE REVIEW

**Review by PencilNavigator — APPROVED** [review]
Checked with DeepL Translator, looks good.

**Comment by PencilNavigator** [comment]
@uncognic you might want to check this.

**Comment by PencilNavigator** [comment]
@osafaimal Remember to add your name to the "Translation contributors" section on the end of the README

**Review by uncognic — COMMENTED** [review]
good

**Review by Xyueta — APPROVED** [review]
Approved

**Pull request merged**
