### PR TITLE
is it worth building more in powershell?

### PR DESCRIPTION
**Pull request by spddl**
Currently 2 times cmd open visible for the user.
With this variant, you only see the GUI.

runHidden.exe src:
```rust
#![windows_subsystem = "windows"]

use std::env::{args, Args};
use std::process::{Command, Stdio};
use std::os::windows::process::CommandExt;

#[allow(unused_must_use)]
fn main() {
    let mut args : Args = args();

    let program = args.nth(1).unwrap();

    let mut programargs: Vec<String> = Vec::new();
    for arg in args {
        programargs.push(arg.to_string());
    }
    println!("program {}", program);
    println!("programargs {:?}", programargs);

    Command::new(program)
        .args(&programargs)
        .stdout(Stdio::null())
        .stderr(Stdio::null())
        .stdin(Stdio::null())
        .creation_flags(0x08000000) // CREATE_NO_WINDOW // https://docs.microsoft.com/en-us/windows/win32/procthread/process-creation-flags
        .spawn();
}

```

### CODE REVIEW

**Review by JayXTQ — COMMENTED** [review]
I would recommend putting the scripts in atlas-config.bat, but also seems very lengthy code just to download a browser via a command as simple as `scoop install x` or `choco install x` but I have no clue how any of this works. I personally think the current system works fine for most users

**Comment by spddl** [comment]
At the moment the "very lengthy code" is hidden in the multichoice.exe.

**Comment by JayXTQ** [comment]
I don't think we should repeat code then to be fair

**Review by Xyueta — APPROVED** [review]

**Comment by spddl** [comment]
The goal should be to do better, right? therefore the question in the title.

**Comment by CYNAR2k** [comment]
I agree!

**Review by SyrmGIT — APPROVED** [review]

**Pull request merged**
