### PR TITLE
[FEATURE] Disabled more services & scheduled tasks and removed more appx.

### PR DESCRIPTION
**Pull request by respberryx**
This pull request introduces the following changes:

1. Disabled additional services and scheduled tasks to optimize system performance.
2. Removed 3 more AppX packages.
3. Disabled suggestions in the Start menu for a cleaner user experience.

These changes aim to further streamline the Atlas OS experience by reducing unnecessary background processes and removing/disabling unwanted features.

### Questions
- [x] Did you test your changes or double-check that they work? (Tested)
- [x] Did you read and follow the [Atlas Contribution Guidelines](https://docs.atlasos.net/contributions/)?

### Describe your pull request
This pull request focuses on system optimization and user interface improvements. By disabling more services and scheduled tasks, we aim to reduce system overhead and improve overall performance. The removal of additional AppX packages helps in decluttering the system and potentially freeing up resources. Lastly, disabling suggestions in the Start menu contributes to a more focused and distraction-free user interface.

I kindly request reviewers to pay special attention to formatting, as there is a chance that I formatted something wrong from contribution guidelines.

Your feedback and suggestions for improvement are greatly appreciated.

### CODE REVIEW

**Comment by JayXTQ** [comment]
Please test your changes before you make a pull request. This won't be pushed until tested.

**Comment by Ast3risk-ops** [comment]
@respberryx Guide: https://docs.atlasos.net/contributing/playbook/#how-to-build-a-playbook

**Comment by respberryx** [comment]
@JayXTQ Thanks, I tested my changes and they work, I also added 1 more thing. 

@Ast3risk-ops Thank's for linking that also.

**Review by JayXTQ — APPROVED** [review]
It looks good generally, you explain some of your changes using comments which is good. I will wait for someone who has more knowledge than me before pushing though as I don't want to cause any issues in future.

**Comment by kamild1996** [comment]
One tidbit I noticed:
https://github.com/Atlas-OS/Atlas/pull/1266/commits/db37064daab65b75f61a9954787814870e1d56d8#diff-3f1c2a4b51355b67ddcb68af122744cf4cd7f48e8abad6215ded9bcc1b8dfa2aR55
Disabling SysMain, which was turned into an optional optimization 0.4.1:
https://github.com/Atlas-OS/Atlas/commit/76cfcaa3630f81ba9dd36ceb48b696b8d8472732

**Comment by Xyueta** [comment]
Hi, thanks for the pr.
Unfortunately, the changes your provided break compatibility, and cause issues with Windows features. Such as, DPS services disables Troubleshooting and causes some Settings pages to break. 
Regardless, we will review and check services, scheduled tasks and other settings.

**Comment by respberryx** [comment]
@Xyueta Thank you for your time and willingness for reviewing this. But please check out the SysMain issue again.

@kamild1996 I see, I commented on it so you can check it out also.

**Pull request closed without merging**
