### PR TITLE
Replace disable/enable files with toggle + fixed typo

### PR DESCRIPTION
**Pull request by 99N9ne99**
Replaced them for consistency

### CODE REVIEW

**Review by JayXTQ — APPROVED** [review]
LGTM

**Comment by Xyueta** [comment]
Can you change to each file?

**Comment by Xyueta** [comment]
merge all disable/enable into one menu.

**Comment by Xyueta** [comment]
This method, it would the best to make all config files like that.

**Comment by JayXTQ** [comment]
We can merge this PR and then work on the rest ourselves

**Pull request merged**
