### PR TITLE
Add Winget Error Checking to Scripts

### PR DESCRIPTION
**Pull request by JustOptimize**
### Questions
- [X] Did you test your changes or double check that they work?
- [X] Did you read and follow the [Atlas Contribution Guidelines](https://docs.atlasos.net/contributions/)?
- [X] Did you commit to the [`dev`](https://github.com/Atlas-OS/Atlas/tree/dev) branch and not [`main`](https://github.com/Atlas-OS/Atlas)?

**Note:** You should commit directly to `main` for translations of the `README.md`.

### Describe your pull request (edited)
Adds Winget error checking in the `Install Open-Shell` and `Install and Replace Task Manager` scripts

This fixes [v03-testing > Install Open-shell script error](https://ptb.discord.com/channels/795710270000332800/1149430331913543770)

### CODE REVIEW

**Comment by he3als** [comment]
This is good, but I'm wondering if the domain that WinGet is trying to pull from to work will ever get changed or if there's other domains required.

**Comment by JustOptimize** [comment]
That same domain gets used by the windows store too, I don't know how often they change domains especially because it's the first one that gets pinged

Here is a full list of domains it reaches when starting the install open shell script
image

**Comment by he3als** [comment]
I think that a better alternative might be simply error checking for WinGet.

**Comment by JustOptimize** [comment]
Working on it 🫡

**Comment by JustOptimize** [comment]
Is checking if the errorlevel is not 0 and if so say something like installation failed?

**Comment by he3als** [comment]
Can you resolve the merge conflicts and add `> nul` to the Open Shell script please?

**Comment by JustOptimize** [comment]
> Can you resolve the merge conflicts

Only those with write accessto this repository can merge pull requests and resolve conflicts.

> Add `> nul` to the Open Shell script please?

Already added that with [a5ace16](https://github.com/Atlas-OS/Atlas/pull/904/commits/a5ace168a5927366390b50b4e1f322c8e624cc11)

**Comment by JustOptimize** [comment]
To be fair I don't know how to resolve conflicts in a pr

**Comment by JustOptimize** [comment]
Figured it out 👍🏻

**Comment by he3als** [comment]
Thank you very much for the PR!

**Pull request merged**
