### PR TITLE
feat: AME Wizard Live Log

### PR DESCRIPTION
**Pull request by the-P1neapple**
### Questions
- [x] Did you test your changes or double check that they work?
- [x] Did you read and follow the [Atlas Contribution Guidelines](https://docs.atlasos.net/contributions/)?
- [x] Did you commit to the [`dev`](https://github.com/Atlas-OS/Atlas/tree/dev) branch and not [`main`](https://github.com/Atlas-OS/Atlas)?

**Note:** You should commit directly to `main` for translations of the `README.md`.

### Describe your pull request

Added a live log output for the AME wizard, this can be helpful with debugging developer playbooks.

### CODE REVIEW

**Comment by the-P1neapple** [comment]
Just want to clarify, I internationally didn't use the cmd action due to the nature of the AME wizard source code not continuing until the log closed. Even with wait set to false, I had other complications.

**Review by JayXTQ — CHANGES_REQUESTED** [review]
Method should be introduced to not run this code if it’s a release. Unless we want to remove this part of the code every time we make a release

**Comment by the-P1neapple** [comment]
Hi Jay, Ive made it so it is edited into the start.yml file via a workflow now. Hope this is what you wanted.

**Comment by the-P1neapple** [comment]
Hold on I just realised I screwed up the revert. Let me recreate this PR

**Pull request closed without merging**
