### PR TITLE
Update translation of zh_CN

### PR DESCRIPTION
**Pull request by alex3236**
- Synchronize with the English documents
- Correct some expressions to fit the Chinese context.

### CODE REVIEW

**Comment by JayXTQ** [comment]
@PencilNavigator this one is for you

**Comment by JayXTQ** [comment]
From now on, can you release one commit to fix all your issues as github actions is currently going mad 😂

**Comment by PencilNavigator** [comment]
I think it was machine-translated since terms like "ISO" can be translated to "镜像“ and certain translations aren't actually translated as the best way.
i'll work on a better version soon, closing it.

**Comment by alex3236** [comment]
> I think it was machine-translated since terms like "ISO" can be translated to "镜像“ and certain translations aren't actually translated as the best way.我认为它是机器翻译的，因为像“ISO”这样的术语可以翻译成“镜像”，而某些翻译实际上并不是最好的翻译方式。 i'll work on a better version soon, closing it.我会尽快开发一个更好的版本，关闭它。

"ISO image" or "ISO 镜像". I don't think image is equivalent to ISO.

**Comment by PencilNavigator** [comment]
整篇读下来有股翻译腔而且有些段落处理的像翻译腔...

**Comment by alex3236** [comment]
> 整篇读下来有股翻译腔而且有些段落处理的像机翻...

嗯 有的语段我遣词不太行 你之后在整吧

**Comment by JayXTQ** [comment]
Lads, please speak english

**Pull request closed without merging**
