### PR TITLE
upadted

### PR DESCRIPTION
**Pull request by David34k**
### Questions
- [x] Did you test your changes or double check that they work?
- [ ] Did you read and follow the [Atlas Contribution Guidelines](https://docs.atlasos.net/contributions/)?
- [x] Did you commit to the [`dev`](https://github.com/Atlas-OS/Atlas/tree/dev) branch and not [`main`](https://github.com/Atlas-OS/Atlas)?

### CODE REVIEW

**Comment by David34k** [comment]
working of it

**Comment by JayXTQ** [comment]
what the hell is this? why did you add so many files and remove so many. please also think of a good title for this pr and not a spelling mistake...

**Comment by JayXTQ** [comment]
oh also, closing because not going to dev

**Comment by Ast3risk-ops** [comment]
> oh also, closing because not going to dev

Github should do that automatically.

**Comment by Ast3risk-ops** [comment]
@JayXTQ Did some digging. This guy forked our code and is trying to use it for his own project. https://refinedos.uk/

https://github.com/David34k/RefinedOS-playbook/tree/main Notice how it's our repo but with the same license and less files. He even has the audacity to make a Ko-Fi.

I'm not exactly sure why he made a PR. It only supports 21h2 LTSC, which is pointless.

**Comment by JayXTQ** [comment]
lmfao doesn't matter. people that don't put in effort won't get anywhere anyway

**Comment by Ast3risk-ops** [comment]
> lmfao doesn't matter. people that don't put in effort won't get anywhere anyway

I know, it's just so weird, also considering the messages he left in the Discord.

**Pull request closed without merging**
