### PR TITLE
Adding Chinese Translation for REARME.md

### PR DESCRIPTION
**Pull request by 0bo**
Hi there,

This is my first time to do this kind of translating task. 

If there is anything inappropriate, please let me know, so I can do better. 

I just did a little search, it seems that I have to be a collaborator to edit **wiki**.

Please let me know if you allow me to do so.

Thank you for you great work!

### CODE REVIEW

**Comment by uncognic** [comment]
There's only 1 wiki per repo, but you could somehow fit it into a markdown file

**Comment by uncognic** [comment]
Also you should change the "Other Language" link in the regular readme to "Chinese Version"

**Comment by PencilNavigator** [comment]
i revieved and seems like there is some part of it not grammarly correct. and some part of it is not translated (like hyperlink) .

**Comment by PencilNavigator** [comment]
i recommend to merge this into a new branch, and if there is any mistake other people can submit a new Pull Request to fix it.

**Comment by 0bo** [comment]
> i revieved and seems like there is some part of it not grammarly correct.

English gramma or Chinese gramma?  I didn't translate eveything directly and as close as original text, but to a version more native Chinese language way.

And you don't have to find someone else, if you find any error, just tell me, I am a native Chinese and would like to finish this quick.

**Comment by 0bo** [comment]
> Also you should change the "Other Language" link in the regular readme to "Chinese Version", and the License section at the end has not been translated

I intended to do both part.

I use the `other language` term, because there are people who use languages other than Chinese. If they want, they may simply do the same and add another language.

The last part is related to legal term, as Github is an USA based Corp, if there is a legal issue in the future, it would be judged in the USA. I believe it is better to keep that way.

**Comment by PencilNavigator** [comment]
> > i revieved and seems like there is some part of it not grammarly correct.
> 
> English gramma or Chinese gramma? I didn't translate eveything directly and as close as original text, but to a version more native Chinese language way.
> 
> And you don't have to find someone else, if you find any error, just tell me, I am a native Chinese and would like to finish this quick.
有些句子读的有点不通顺，还有一些地方没翻译过来

我已经交了另一个修改版的PR了。

**Comment by 0bo** [comment]
> > > i revieved and seems like there is some part of it not grammarly correct.
> > 
> > 
> > English gramma or Chinese gramma? I didn't translate eveything directly and as close as original text, but to a version more native Chinese language way.
> > And you don't have to find someone else, if you find any error, just tell me, I am a native Chinese and would like to finish this quick.
> 
> 有些句子读的有点不通顺（像机翻），还有一些地方没翻译过来
> 
> 我已经交了另一个修改版的PR了。最好是让Owner先Merge到另一个分支，好做修改。

嗯嗯，我看了下，挺好的。一个人一种语言风格吧。

但是关于土豆那部分，我觉得你可以再调整一下，没有体现出土豆服务器那个韵味。原文应该是说，这个系统可以更好的发挥计算机的性能，一定程度弥合土豆计算机和游戏计算机之间的差距，争取玩家间更加平等。

**Comment by PencilNavigator** [comment]
> > Also you should change the "Other Language" link in the regular readme to "Chinese Version", and the License section at the end has not been translated
> 
> I intended to do both part.
> 
> I use the `other language` term, because there are people who use languages other than Chinese. If they want, they may simply do the same and add another language.
> 
> The last part is related to legal term, as Github is an USA based Corp, if there is a legal issue in the future, it would be judged in the USA. I believe it is better to keep that way.

这个解决方法很简单，参考GPL License的翻译策略，在英文和中文界面声明任何翻译仅供参考，以英文为准。

**Comment by 0bo** [comment]
> > > Also you should change the "Other Language" link in the regular readme to "Chinese Version", and the License section at the end has not been translated
> > 
> > 
> > I intended to do both part.
> > I use the `other language` term, because there are people who use languages other than Chinese. If they want, they may simply do the same and add another language.
> > The last part is related to legal term, as Github is an USA based Corp, if there is a legal issue in the future, it would be judged in the USA. I believe it is better to keep that way.
> 
> 这个解决方法很简单，参考GPL License的翻译策略，在英文和中文界面声明任何翻译仅供参考，以英文为准。

对。。。但。。。那不是麻烦么。。。让中文用户看懂主要内容才是咱们做个的目的吧 :smiling_face_with_tear:

**Comment by PencilNavigator** [comment]
> > > > Also you should change the "Other Language" link in the regular readme to "Chinese Version", and the License section at the end has not been translated
> > > 
> > > 
> > > I intended to do both part.
> > > I use the `other language` term, because there are people who use languages other than Chinese. If they want, they may simply do the same and add another language.
> > > The last part is related to legal term, as Github is an USA based Corp, if there is a legal issue in the future, it would be judged in the USA. I believe it is better to keep that way.
> > 
> > 
> > 这个解决方法很简单，参考GPL License的翻译策略，在英文和中文界面声明任何翻译仅供参考，以英文为准。
> 
> 对。。。但。。。那不是麻烦么。。。让中文用户看懂主要内容才是咱们做个的目的吧 🥲

加一句话就ok了，只用表明免责声明的翻译是非正式的。

**Comment by 0bo** [comment]
> > > > > i revieved and seems like there is some part of it not grammarly correct.
> > > > 
> > > > 
> > > > English gramma or Chinese gramma? I didn't translate eveything directly and as close as original text, but to a version more native Chinese language way.
> > > > And you don't have to find someone else, if you find any error, just tell me, I am a native Chinese and would like to finish this quick.
> > > 
> > > 
> > > 有些句子读的有点不通顺（像机翻），还有一些地方没翻译过来
> > > 我已经交了另一个修改版的PR了。最好是让Owner先Merge到另一个分支，好做修改。
> > 
> > 
> > 翻译都是我自己翻的，也没几个字。。。
> > 嗯嗯，我看了下，挺好的。一个人一种语言风格吧。
> > 但是关于土豆那部分，我觉得你可以再调整一下，没有体现出土豆服务器那个韵味。原文应该是说，这个系统可以更好的发挥计算机的性能，一定程度弥合土豆计算机和游戏计算机之间的差距，争取玩家间更加平等。
> 
> 这句话已经修改了。 土豆服务器（妈的，育碧！）这个翻法根据个人理解不同可以翻成很多种，毕竟有差。

哈哈哈！上图！

**Pull request closed without merging**
