### PR TITLE
SOFTWARE.ps1: Fix VLC Download

### PR DESCRIPTION
**Pull request by sakshiagrwal**
### Questions
- [x] Did you test your changes or double check that they work?
- [x] Did you read and follow the [Atlas Contribution Guidelines](https://docs.atlasos.net/contributions/)?
- [x] Did you commit to the [`dev`](https://github.com/Atlas-OS/Atlas/tree/dev) branch and not [`main`](https://github.com/Atlas-OS/Atlas)?

**Note:** You should commit directly to `main` for translations of the `README.md`.

### Describe your pull request

Fixes this error:

Err

### CODE REVIEW

**Comment by Ast3risk-ops** [comment]
Invalid description: the download link is *unchanged*.

**Comment by sakshiagrwal** [comment]
> Invalid description: the download link is _unchanged_.
> 
> What does this PR actually do.

The original code giving this error:

Err

I know I can modify the `Invoke-WebRequest` line to include the `-UseBasicParsing` parameter to avoid using the Internet Explorer engine. However, I believe the updated lines are better.

**Comment by Ast3risk-ops** [comment]
> > Invalid description: the download link is _unchanged_.
> > What does this PR actually do.
> 
> The original code giving this error:
> 
> Err
> 
> I know I can modify the `Invoke-WebRequest` line to include the `-UseBasicParsing` parameter to avoid using the Internet Explorer engine. However, I believe the updated lines are better.

Put that under PR description in your PR (go to the first message > 3 dots > edit)

**Comment by he3als** [comment]
Thank you! We'll also implement native ARM64 detection for these applications.

**Comment by sakshiagrwal** [comment]
> Thank you! We'll also implement native ARM64 detection for these applications.

NP :) 
Please review this: https://github.com/sakshiagrwal/Atlas/commit/9d6598ed18b367fdd62e1c22b36b2594042d0a99. If it's okay, I'll update the apps and create a PR.

**Pull request merged**
