### PR TITLE
Add bosnian (bosanski) translation

### PR DESCRIPTION
**Pull request by terminalarch**
Both the translation itself and added bosnian to the list of languages

### CODE REVIEW

**Comment by terminalarch** [comment]
nvm prolly shoulda read the closed pull requests

**Review by PencilNavigator — APPROVED** [review]
LGTM
(Edit: found some issues that violate our Translation README guidelines. Delted the translation)

**Comment by PencilNavigator** [comment]
Found some issues that violate our Translation README guidelines. Delted the translation.
Please read the README translation guideline before commiting.

**Comment by terminalarch** [comment]
Thanks for telling me. I assume I got the "Do not translate the disclaimer" part wrong?

**Comment by PencilNavigator** [comment]
Yes. and you also changed the format.

**Pull request merged**
